from setuptools import find_packages, setup

setup(
    name="esdglider",
    version="0.2.0-dev",
    description="Utility functions for processing ESD glider data",
    url="http://github.com/swfsc/glider-utils",
    author="Sam Woodman",
    author_email="sam.woodman@noaa.gov",
    license="Apache 2.0",
    packages=find_packages(exclude=('tests', 'docs')),
    package_data={"esdglider": ["esdglider/data/*"]},
    include_package_data=True,
    python_requires=">=3.10",
    install_requires=[
        "google-crc32c>=1.1",
        "google-cloud-secret-manager>=2.12",
        "numpy",
        "pandas",
        "xarray",
        "gsw",
        "pyyaml",
        "pyglider",
        "netCDF4",
        "SQLAlchemy",
        "cartopy",
        "cmocean",
        "matplotlib",
        "glidertools",
        "skyfield", 
        "timezonefinder", 
    ],
    zip_safe=False,
)
